branches:
  only:
    - master

sudo: required

language: java

jdk: openjdk17

services:
  - docker

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1 --no-include-email)
  - ./gradlew build
  - docker build -t tasks .
  - docker tag tasks:latest 902382300595.dkr.ecr.us-east-1.amazonaws.com/tasks:latest
  - docker push 902382300595.dkr.ecr.us-east-1.amazonaws.com/tasks:latest

notifications:
  webhooks:
    urls:
      - https://resnyx.sergeybochkov.com/travis
