---
- hosts: server
  tasks:
    - file: path=/tmp/tasks_deploy state=directory
    - copy: src=../build/libs/tasks-all.jar dest=/tmp/tasks_deploy/tasks.jar
    - copy: src=Dockerfile dest=/tmp/tasks_deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker_container:
        name: tasks
        state: absent

    - name: delete docker image
      docker_image:
        path: /tmp/tasks_deploy
        name: tasks
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/tasks_deploy
        name: tasks

    - name: clean
      file:
        state: absent
        path: /tmp/tasks_deploy
