## run se task
POST http://localhost:8088/api/run
Content-Type: application/json

{"id": ["5974774d8af5e613d909123f"]}

### run obl task
POST http://localhost:8088/api/run
Content-Type: application/json

{"id":["59902e59d620293af34ada05"]}

### run lostfilm task
POST http://localhost:8088/api/run
Content-Type: application/json

{"id":["5e2b9ef2df1fa70aa71d9584"]}

###